"""Optional packs (Graphify, Obsidian) for `ai-pipeline pack ...`.

Rules (from the ai-pipeline-sandbox / ai-pipeline-graph skills):
- nothing is installed without an explicit confirmation (prompt, or --yes);
- Python packages go into an isolated venv inside the project (.venv-graphify), never the host Python;
- Graphify runs with --code-only and with every LLM API key removed from the environment;
- we never run `graphify claude|codex|... install` (they edit AGENTS.md/CLAUDE.md/hooks);
- existing user files (.graphifyignore, vault/ not generated by us) are never overwritten.
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

GRAPHIFY_PKG = "graphifyy"  # double y on PyPI; the command is `graphify`
GRAPHIFY_VERSION = "0.9.74"  # version verified with the workflow
VENV = ".venv-graphify"
LOCK = ".venv-graphify-requirements.lock"
API_KEYS = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY", "GOOGLE_API_KEY",
            "MOONSHOT_API_KEY", "DEEPSEEK_API_KEY", "AZURE_OPENAI_API_KEY", "AWS_ACCESS_KEY_ID"]
FALLBACK_IGNORE = """# Graphify scope: code only; never dataset/images/checkpoints/secrets/derived/mirrors
.git/
.venv*/
node_modules/
graphify-out/
vault/
__pycache__/
runs/*/data/
runs/*/notebook/export/
.claude/skills/
.agents/skills/
.env*
*.pt
*.pth
*.pdparams
*.onnx
*.npy
*.jpg
*.png
*.pdf
"""


def confirm(question, yes):
    if yes:
        return True
    if not sys.stdin.isatty():
        print(f"{question}\n  -> khong co terminal tuong tac: chay lai voi --yes de dong y.")
        return False
    try:
        return input(f"{question} [y/N] ").strip().lower() in ("y", "yes", "c", "co")
    except EOFError:
        print("  -> khong doc duoc cau tra loi: chay lai voi --yes de dong y.")
        return False


def venv_bin(project, name):
    d = project / VENV / ("Scripts" if os.name == "nt" else "bin")
    for cand in (name + ".exe", name):
        if (d / cand).is_file():
            return d / cand
    return None


def find_python310():
    """Graphify needs Python >= 3.10; prefer the interpreter running the CLI."""
    if sys.version_info >= (3, 10):
        return [sys.executable]
    cands = [["py", f"-3.{m}"] for m in (13, 12, 11, 10)] if os.name == "nt" else []
    cands += [[f"python3.{m}"] for m in (13, 12, 11, 10)]
    for c in cands:
        if shutil.which(c[0]):
            try:
                r = subprocess.run([*c, "-c", "import sys;print(sys.version_info>=(3,10))"],
                                   capture_output=True, text=True, timeout=20)
                if r.stdout.strip() == "True":
                    return c
            except Exception:
                pass
    return None


def clean_env():
    env = {k: v for k, v in os.environ.items() if k not in API_KEYS}
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def load_manifest(project):
    p = project / ".ai-pipeline.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else None


def record_pack(project, name, info):
    m = load_manifest(project)
    if m is None:
        return
    m.setdefault("packs", {})[name] = info
    (project / ".ai-pipeline.json").write_text(json.dumps(m, indent=2, sort_keys=True), encoding="utf-8")


def find_obsidian():
    if sys.platform == "win32":
        for base in (os.environ.get("LOCALAPPDATA"), os.environ.get("ProgramFiles")):
            if base and (Path(base) / "Obsidian" / "Obsidian.exe").is_file():
                return str(Path(base) / "Obsidian" / "Obsidian.exe")
    elif sys.platform == "darwin":
        for p in ("/Applications/Obsidian.app", str(Path.home() / "Applications" / "Obsidian.app")):
            if Path(p).exists():
                return p
    else:
        if shutil.which("obsidian"):
            return shutil.which("obsidian")
        if shutil.which("flatpak"):
            r = subprocess.run(["flatpak", "list", "--app", "--columns=application"], capture_output=True, text=True)
            if "md.obsidian.Obsidian" in r.stdout:
                return "flatpak:md.obsidian.Obsidian"
        if shutil.which("snap"):
            r = subprocess.run(["snap", "list"], capture_output=True, text=True)
            if any(l.split()[:1] == ["obsidian"] for l in r.stdout.splitlines()):
                return "snap:obsidian"
    return None


def obsidian_install_cmd():
    if sys.platform == "win32" and shutil.which("winget"):
        return ["winget", "install", "--id", "Obsidian.Obsidian", "-e"]
    if sys.platform == "darwin" and shutil.which("brew"):
        return ["brew", "install", "--cask", "obsidian"]
    if sys.platform.startswith("linux") and shutil.which("flatpak"):
        return ["flatpak", "install", "-y", "flathub", "md.obsidian.Obsidian"]
    return None


def status(project):
    gv = venv_bin(project, "graphify")
    print("Packs:")
    if gv:
        r = subprocess.run([str(gv), "--version"], capture_output=True, text=True, env=clean_env())
        print(f"  graphify : CAI ({(r.stdout or r.stderr).strip()[:40]}) @ {VENV}")
    else:
        print(f"  graphify : chua cai   -> ai-pipeline pack install graphify")
    out = project / "graphify-out" / "graph.json"
    print(f"             graph  : {'co' if out.is_file() else 'chua build'}   -> ai-pipeline pack build graphify")
    ob = find_obsidian()
    print(f"  obsidian : {'CAI (' + ob + ')' if ob else 'chua cai (ung dung desktop)'}")
    vault = project / "vault"
    print(f"             vault  : {'co' if vault.is_dir() else 'chua build'}   -> ai-pipeline pack build obsidian")
    return 0


def install_graphify(project, yes, version, extras):
    spec = f"{GRAPHIFY_PKG}{('[' + extras + ']') if extras else ''}=={version}"
    venv = project / VENV
    if venv_bin(project, "graphify"):
        print(f"graphify da co trong {VENV}. Dung `pack build graphify`.")
        return 0
    py = find_python310()
    if not py:
        print("Graphify can Python >= 3.10 nhung khong tim thay. Cai Python 3.10+ roi chay lai.")
        return 1
    q = (f"Cai `{spec}` (PyPI, ban ghim phien ban) vao moi truong ao co lap {venv}\n"
         f"  - khong dung Python he thong; pip chay trong venv; can mang toi pypi.org\n"
         f"  - khong chay `graphify claude|codex install` (khong sua AGENTS.md/CLAUDE.md)")
    if not confirm(q, yes):
        print("Da huy, khong cai gi.")
        return 1
    print(f"Tao venv bang {' '.join(py)} ...")
    if subprocess.call([*py, "-m", "venv", str(venv)]) != 0:
        return 1
    vpy = venv / ("Scripts" if os.name == "nt" else "bin") / ("python.exe" if os.name == "nt" else "python")
    if subprocess.call([str(vpy), "-m", "pip", "install", "--disable-pip-version-check", spec]) != 0:
        print(f"pip install that bai. Venv {venv} giu nguyen de ban xem; xoa bang `pack uninstall graphify`.")
        return 1
    freeze = subprocess.run([str(vpy), "-m", "pip", "freeze"], capture_output=True, text=True).stdout
    lock = project / LOCK
    if not lock.exists():
        lock.write_text(freeze, encoding="utf-8")
    ign = project / ".graphifyignore"
    if not ign.exists():
        tpl = project / "templates" / "graphifyignore.template"
        ign.write_text(tpl.read_text(encoding="utf-8") if tpl.is_file() else FALLBACK_IGNORE, encoding="utf-8")
        print("  tao .graphifyignore (loai du lieu/anh/checkpoint/secrets)")
    else:
        print("  .graphifyignore da co -> giu nguyen (kiem tra no loai du lieu/secrets)")
    record_pack(project, "graphify", {"package": spec, "venv": VENV})
    print(f"Xong. Phien ban: {spec}. Lock: {LOCK}\n"
          f"Them `{VENV}/`, `graphify-out/`, `vault/` vao .gitignore. Ghi vao decisions.md cua run: da duoc duyet, vi tri, phien ban.\n"
          f"Tiep: ai-pipeline pack build graphify")
    return 0


def build_graphify(project):
    gv = venv_bin(project, "graphify")
    if not gv:
        print("graphify chua cai: ai-pipeline pack install graphify")
        return 1
    env = clean_env()
    steps = [["extract", ".", "--code-only", "--no-gitignore"], ["cluster-only", ".", "--no-label"]]
    for s in steps:
        print("graphify " + " ".join(s) + "   (--code-only, khong gui gi ra ngoai, API key da go khoi env)")
        if subprocess.call([str(gv), *s], cwd=str(project), env=env) != 0:
            print("graphify loi; xem log phia tren (kiem tra `graphify --help` cua phien ban da cai).")
            return 1
    rep = project / "graphify-out" / "GRAPH_REPORT.md"
    print(f"Xong. Doc {rep if rep.is_file() else 'graphify-out/'}; truy van: {gv} query \"<cau hoi>\"")
    return 0


def install_obsidian(project, yes):
    ob = find_obsidian()
    if ob:
        print(f"Obsidian da cai: {ob}")
        return 0
    cmd = obsidian_install_cmd()
    print("Obsidian la ung dung desktop (https://obsidian.md/download).")
    if not cmd:
        print("  Khong thay winget/brew/flatpak. Tai ban cai dat tai https://obsidian.md/download roi mo thu muc vault/ nhu mot vault.")
        return 0
    if not confirm("Cai Obsidian toan he thong bang: " + " ".join(cmd), yes):
        print("Da huy. Ban co the tu cai bang lenh tren hoac tai tu trang chu.")
        return 1
    rc = subprocess.call(cmd)
    print("Xong." if rc == 0 else f"Lenh tra ve {rc}; hay cai thu cong tai https://obsidian.md/download")
    if rc == 0:
        record_pack(project, "obsidian", {"installed_by": " ".join(cmd)})
    return rc


def build_obsidian(project):
    script = project / "scripts" / "obsidian_vault.py"
    if not script.is_file():
        print("Thieu scripts/obsidian_vault.py: chay `ai-pipeline init` truoc.")
        return 1
    cmd = [sys.executable, str(script)]
    gv = venv_bin(project, "graphify")
    if gv and (project / "graphify-out" / "graph.json").is_file():
        cmd += ["--graphify", str(gv)]
    else:
        print("  (chua co graph code: vault chi gom tai lieu/so thi nghiem; chay `pack build graphify` truoc de them code graph)")
    rc = subprocess.call(cmd, cwd=str(project), env=clean_env())
    if rc == 0:
        print(f"Mo thu muc {project / 'vault'} nhu mot vault trong Obsidian (Open folder as vault) -> Graph view.")
        if not find_obsidian():
            print("Obsidian chua cai: ai-pipeline pack install obsidian")
    return rc


def uninstall_graphify(project, yes):
    venv = project / VENV
    if not venv.is_dir():
        print("Khong co venv graphify.")
        return 0
    if not confirm(f"Xoa {venv} (venv do ai-pipeline tao; graphify-out/ va .graphifyignore giu nguyen)?", yes):
        return 1
    shutil.rmtree(venv)
    print("Da xoa venv.")
    return 0


def run(a):
    project = Path(a.path).resolve()
    act, name = a.action, a.pack
    if act == "list" or act == "status":
        return status(project)
    if name is None:
        print("Thieu ten pack: graphify | obsidian")
        return 2
    table = {
        ("install", "graphify"): lambda: install_graphify(project, a.yes, a.version or GRAPHIFY_VERSION, a.extras),
        ("build", "graphify"): lambda: build_graphify(project),
        ("uninstall", "graphify"): lambda: uninstall_graphify(project, a.yes),
        ("install", "obsidian"): lambda: install_obsidian(project, a.yes),
        ("build", "obsidian"): lambda: build_obsidian(project),
    }
    fn = table.get((act, name))
    if not fn:
        print(f"Khong ho tro `pack {act} {name}`.")
        return 2
    return fn()
